apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ldap
  name: ldap-data
  namespace: auth
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-path
