apiVersion: v1
data:
  accessKey: bW9jay1hY2Nlc3M=
  resticPassword: bW9jay1yZXN0aWMtcHc=
  secretKey: bW9jay1zZWNyZXQ=
kind: Secret
metadata:
  name: ldap-restic-config
  namespace: auth
type: Opaque
