apiVersion: v1
kind: Service
metadata:
  labels:
    name: ldap
  name: ldap
  namespace: auth
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: ldaps
    port: 636
    targetPort: 1636
  - name: ldap
    port: 389
    targetPort: 1389
  selector:
    app: ldap
    name: ldap
  sessionAffinity: ClientIP
